format_version = 2

[apps.Kraken]
identifier = 'foundation.wabi.Kraken'
product = 'Kraken'
version = '1.0.0'
category = 'public.app-category.graphics-design'
icon = "kraken.png"

[apps.Kraken.plist]
commit = '$(COMMIT_HASH)'
CFBundleURLTypes = [ { type = "dict", value = { CFBundleTypeRole = 'Viewer', CFBundleURLName = 'Kraken', CFBundleURLSchemes = [ 'kraken' ] } } ]

