name: macOS arm64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: pwsh

    steps:
    - uses: actions/checkout@v3

    - name: Source Zsh
      run: zsh

    - name: Ensure Powershell
      run: pwsh

    - name: Build
      run: cd ${{github.workspace}} && make release

    - name: Notarize with Apple Inc.
      run: pwsh -Command AppleBundleAndNotarize

    - uses: actions/upload-artifact@v3
      with:
        name: kraken-1.50a-macos-arm64-${{github.sha}}.dmg
        path: ~/actions-runner/_work/Kraken/build_darwin_release/kraken-1.50a-macos-arm64.dmg

    - name: Cleanup
      run: rm ${{github.workspace}}/../build_darwin_release/kraken-1.50a-macos-arm64.dmg
